# Generated by Django 3.2.9 on 2022-01-13 18:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_pago_id_alter_producto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
